# Generated by Django 3.2.8 on 2021-10-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_productos',
            name='nom_tipo_producto',
            field=models.CharField(max_length=60, unique=True, verbose_name='Producto'),
        ),
    ]
